# Generated by Django 5.2.1 on 2025-05-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.CharField(max_length=100)),
                ('rest_days', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('end_time', models.CharField(max_length=100)),
                ('is_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clinic/')),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='clinic/')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_by_category', to='clinic_app.category')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_by_doctors', to='clinic_app.category')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_by_schedule', to='clinic_app.category')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_by_services', to='clinic_app.category')),
            ],
        ),
    ]
