services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: clinic_project
      POSTGRES_USER: clinic_project
      POSTGRES_PASSWORD: clinic_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    image: clinic_project:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:




